# Data frame

In [ ]:
combining multiple series is data frame

## creating a data frame

In [2]:
import numpy as np
import pandas as pd

In [8]:
data ={
    "name":['John',"Anna","Peter","linda"],
    "age":[28,34,29,42],
    "city": ["New York","Paris","Berlin","london"],
    "salary": [65000,70000,62000,85000]
}
df=pd.DataFrame(data)

In [9]:
df

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  linda   42    london   85000

In [14]:
data_list =[
    ['John',"Anna","Peter","linda"],
    [28,34,29,42],
     ["New York","Paris","Berlin","london"],
     [65000,70000,62000,85000]
]

In [15]:
col=["P_name"	,"p_age"	,"p_city"	,"p_salary"]
df2=pd.DataFrame(data_list,columns=col)
df2

     P_name  p_age  p_city p_salary
0      John   Anna   Peter    linda
1        28     34      29       42
2  New York  Paris  Berlin   london
3     65000  70000   62000    85000

# selection and indexing of columns

In [16]:
df2

     P_name  p_age  p_city p_salary
0      John   Anna   Peter    linda
1        28     34      29       42
2  New York  Paris  Berlin   london
3     65000  70000   62000    85000

In [18]:
df2["P_name"]

0        John
1          28
2    New York
3       65000
Name: P_name, dtype: object

In [19]:
df2["p_city"]

0     Peter
1        29
2    Berlin
3     62000
Name: p_city, dtype: object

In [20]:
df2[["P_name","p_age"]]

     P_name  p_age
0      John   Anna
1        28     34
2  New York  Paris
3     65000  70000

# creating a new columnm

In [23]:
df2["desigination"] = ["AiMl engg","data Engg","Data analysist","python dev"]
df2

     P_name  p_age  p_city p_salary    desigination
0      John   Anna   Peter    linda       AiMl engg
1        28     34      29       42       data Engg
2  New York  Paris  Berlin   london  Data analysist
3     65000  70000   62000    85000      python dev

# removing a clmm

In [26]:
df2.drop("desigination",axis=1)

     P_name  p_age  p_city p_salary
0      John   Anna   Peter    linda
1        28     34      29       42
2  New York  Paris  Berlin   london
3     65000  70000   62000    85000

In [27]:
df2

     P_name  p_age  p_city p_salary    desigination
0      John   Anna   Peter    linda       AiMl engg
1        28     34      29       42       data Engg
2  New York  Paris  Berlin   london  Data analysist
3     65000  70000   62000    85000      python dev

In [28]:
df2.drop("desigination",axis=1,inplace=True)

In [29]:
df2

     P_name  p_age  p_city p_salary
0      John   Anna   Peter    linda
1        28     34      29       42
2  New York  Paris  Berlin   london
3     65000  70000   62000    85000

# selecting a row

In [30]:
df

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  linda   42    london   85000

In [32]:
df.loc[0]

name          John
age             28
city      New York
salary       65000
Name: 0, dtype: object

In [33]:
df.loc[[1,3]]

    name  age    city  salary
1   Anna   34   Paris   70000
3  linda   42  london   85000

In [34]:
df.iloc[3]

name       linda
age           42
city      london
salary     85000
Name: 3, dtype: object

# selecting rows and subsets of columns

In [35]:
df

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  linda   42    london   85000

In [39]:
df.loc[[0,1]][["name","salary"]]

   name  salary
0  John   65000
1  Anna   70000

In [40]:
df.loc[[2,3]][["name","age"]]

    name  age
2  Peter   29
3  linda   42

# conditional stTEMENTS

In [41]:
df

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  linda   42    london   85000

In [42]:
# age greater thsn 30
df[df["age"]>30]

    name  age    city  salary
1   Anna   34   Paris   70000
3  linda   42  london   85000

In [45]:
df[(df["age"]>30) & (df['city']=="Paris")]

   name  age   city  salary
1  Anna   34  Paris   70000

In [ ]:
[]