# merging 2 dataframes

In [1]:
import numpy as np 
import pandas as pd

In [10]:
emp={
    "emp_id":[1,2,3,4,5],
    "name":["dhiraj","aman","suyash","sohan","pratik"],
    "dep":["HR","IT","Finance","IT","HR"]
}

salaries={
    "emp_id":[1,2,3,6,7],
    "salary":[60000,50000,55000,70000,90000],
    "bonus":[500,600,700,800,900]
    
    
}

emp=pd.DataFrame(emp)
salaries=pd.DataFrame(salaries)

In [13]:
emp

   emp_id    name      dep
0       1  dhiraj       HR
1       2    aman       IT
2       3  suyash  Finance
3       4   sohan       IT
4       5  pratik       HR

In [12]:
salaries

   emp_id  salary  bonus
0       1   60000    500
1       2   50000    600
2       3   55000    700
3       6   70000    800
4       7   90000    900

In [14]:
pd.merge(emp,salaries)

   emp_id    name      dep  salary  bonus
0       1  dhiraj       HR   60000    500
1       2    aman       IT   50000    600
2       3  suyash  Finance   55000    700

In [15]:
pd.merge(emp,salaries,on="emp_id")

   emp_id    name      dep  salary  bonus
0       1  dhiraj       HR   60000    500
1       2    aman       IT   50000    600
2       3  suyash  Finance   55000    700

In [16]:
pd.merge(emp,salaries,on="emp_id",how="inner")

   emp_id    name      dep  salary  bonus
0       1  dhiraj       HR   60000    500
1       2    aman       IT   50000    600
2       3  suyash  Finance   55000    700

In [17]:
pd.merge(emp,salaries,on="emp_id",how="outer")

   emp_id    name      dep   salary  bonus
0       1  dhiraj       HR  60000.0  500.0
1       2    aman       IT  50000.0  600.0
2       3  suyash  Finance  55000.0  700.0
3       4   sohan       IT      NaN    NaN
4       5  pratik       HR      NaN    NaN
5       6     NaN      NaN  70000.0  800.0
6       7     NaN      NaN  90000.0  900.0

In [19]:
emp

   emp_id    name      dep
0       1  dhiraj       HR
1       2    aman       IT
2       3  suyash  Finance
3       4   sohan       IT
4       5  pratik       HR

In [20]:
salaries

   emp_id  salary  bonus
0       1   60000    500
1       2   50000    600
2       3   55000    700
3       6   70000    800
4       7   90000    900

In [18]:
pd.merge(emp,salaries,on="emp_id",how="left")

   emp_id    name      dep   salary  bonus
0       1  dhiraj       HR  60000.0  500.0
1       2    aman       IT  50000.0  600.0
2       3  suyash  Finance  55000.0  700.0
3       4   sohan       IT      NaN    NaN
4       5  pratik       HR      NaN    NaN

In [22]:
pd.merge(emp,salaries,on="emp_id",how="right")

   emp_id    name      dep  salary  bonus
0       1  dhiraj       HR   60000    500
1       2    aman       IT   50000    600
2       3  suyash  Finance   55000    700
3       6     NaN      NaN   70000    800
4       7     NaN      NaN   90000    900

# concatinaition

In [23]:
df1=pd.DataFrame({
    "A":["A0","A1","A2"],
    "B":["B0","B1","B2"],
    "C":["C0","C1","C2"]
}) 

df2=pd.DataFrame({
    "A":["A3","A4","A5"],
    "B":["B3","B4","B5"],
    "C":["C3","C4","C5"],
})

In [24]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [25]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [26]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [27]:
pd.concat([df2,df1])

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [28]:
pd.concat([df1,df2],axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

**joining 2 data frames**

In [29]:
df1=pd.DataFrame({
    "name":["dhiraj","shekhar","sam"]
},index=[1,2,3])

df2=pd.DataFrame({
    "score":[85,90,70]
},index=[2,3,4])

In [30]:
df1

      name
1   dhiraj
2  shekhar
3      sam

In [31]:
df2

   score
2     85
3     90
4     70

In [32]:
df1.join(df2)

      name  score
1   dhiraj    NaN
2  shekhar   85.0
3      sam   90.0

In [33]:
df1.join(df2,how="outer")

      name  score
1   dhiraj    NaN
2  shekhar   85.0
3      sam   90.0
4      NaN   70.0

In [34]:
df1.join(df2,how="inner")

      name  score
2  shekhar     85
3      sam     90