# Missing Data

In [2]:
import numpy as np 
import pandas as pd

## Finding Missing Data

In [20]:
data={
    'A':[1,2,np.nan,4,5],
    "B":[np.nan,2,3,4,5],
    "C":[np.nan,2,3,4,5],
    "D":[1,np.nan,np.nan,np.nan,5],
    
}

In [21]:
df=pd.DataFrame(data)
df

     A    B    C    D
0  1.0  NaN  NaN  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  4.0  NaN
4  5.0  5.0  5.0  5.0

In [9]:
df.isna()

       A      B      C      D
0  False   True   True  False
1  False  False  False   True
2   True  False  False   True
3  False  False  False   True
4  False  False  False  False

In [10]:
df.isna().sum()

A    1
B    1
C    1
D    3
dtype: int64

In [11]:
df.isna().any()

A    True
B    True
C    True
D    True
dtype: bool

## removing missing Data

In [12]:
df

     A    B    C    D
0  1.0  NaN  NaN  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  4.0  NaN
4  5.0  5.0  5.0  5.0

In [22]:
df.dropna()

     A    B    C    D
4  5.0  5.0  5.0  5.0

In [23]:
df

     A    B    C    D
0  1.0  NaN  NaN  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  4.0  NaN
4  5.0  5.0  5.0  5.0

In [24]:
df.dropna(thresh=3)

     A    B    C    D
1  2.0  2.0  2.0  NaN
3  4.0  4.0  4.0  NaN
4  5.0  5.0  5.0  5.0

# filling the missing data

In [25]:
df

     A    B    C    D
0  1.0  NaN  NaN  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  4.0  NaN
4  5.0  5.0  5.0  5.0

In [26]:
df.fillna(0)

     A    B    C    D
0  1.0  0.0  0.0  1.0
1  2.0  2.0  2.0  0.0
2  0.0  3.0  3.0  0.0
3  4.0  4.0  4.0  0.0
4  5.0  5.0  5.0  5.0

In [27]:
df

     A    B    C    D
0  1.0  NaN  NaN  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  4.0  NaN
4  5.0  5.0  5.0  5.0

In [29]:
values ={"A":0,"B":100,"C":1000,"D":10000 }
df.fillna(value=values)

     A      B       C        D
0  1.0  100.0  1000.0      1.0
1  2.0    2.0     2.0  10000.0
2  0.0    3.0     3.0  10000.0
3  4.0    4.0     4.0  10000.0
4  5.0    5.0     5.0      5.0

In [30]:
df

     A    B    C    D
0  1.0  NaN  NaN  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  4.0  NaN
4  5.0  5.0  5.0  5.0

In [31]:
df.fillna(df.mean())

     A    B    C    D
0  1.0  3.5  3.5  1.0
1  2.0  2.0  2.0  3.0
2  3.0  3.0  3.0  3.0
3  4.0  4.0  4.0  3.0
4  5.0  5.0  5.0  5.0